### ISSUE TITLE
will-change使用

### ISSUE THREAD

**Issue by 13916253446** [13916253446/blog#16]
当我们通过某些行为（点击、移动或滚动）触发页面进行大面积绘制的时候，浏览器往往是没有准备的，只能被动使用`CPU`去计算与重绘，由于没有事先准备，应付渲染够呛，于是掉帧，于是卡顿。而`will-change`则是真正的行为触发之前告诉浏览器：“浏览器同学，我待会儿就要变形了，你心理和生理上都准备准备”。于是乎，浏览器同学把`GPU`给拉上了，从容应对即将到来的变形

### 属性：
```css
/* 关键字值 */
will-change: auto;
will-change: scroll-position;
will-change: contents;
will-change: transform;        /* <custom-ident>示例 */
will-change: opacity;          /* <custom-ident>示例 */
will-change: left, top;        /* 两个<animateable-feature>示例 */

/* 全局值 */
will-change: inherit;
will-change: initial;
will-change: unset;
```
#### auto
就跟`width:auto`一样，实际上没什么卵用，昨天嘛，估计就是用来重置其他比较屌的值

#### scroll-position
告诉浏览器，我要开始翻滚了

#### contents
告诉浏览器，内容要动画或变化了。

#### <custom-ident>
顾名思意，自定义的识别。非规范称呼，应该是`MDN`自己的称呼，以后可能会明确写入规范。比方说`animation`的名称，计数器`counter-reset`, `counter-increment`定义的名称等等。

上面展示了2个例子，一个是`transform`一个是`opacity`，都是CSS3动画常用属性。如果给定的属性是缩写，则所有缩写相关属性变化都会触发。同时不能是以下这些关键字值：`unset`, `initial`, `inherit`, `will-change`, `auto`, `scroll-position`, 或 `contents`

#### <animateable-feature>
可动画的一些特征值。比方说`left`, `top`, `margin`之类。移动端，非`transform`, `opacity`属性的动画性能都是低下的，所以都是建议避免使用`left/top/margin`之流进行唯一等。但是，如果你觉得自己是`margin`属性奶大的，非要使用之，试试加个`will-change:margin`说不定也会很流畅（移动端目前支持还不是很好）

#### 就目前而言，使用的基本上都是：
```css
.example {
  will-change: transform;
}
```

#### 不要这样直接写在默认状态中，因为`will-change`会一直挂着：
```css
will-change {
  will-change: transform;
  transition: transform 0.3s;
}
.will-change:hover {
  transform: scale(1.5);
}
```
可以让父元素`hover`的时候，声明`will-change`，这样，移出的时候就会自动`remove`，触发的范围基本上是有效元素范围。
```css
.will-change-parent:hover .will-change {
  will-change: transform;
}
.will-change {
  transition: transform 0.3s;
}
.will-change:hover {
  transform: scale(1.5);
}
```
如果使用`JS`添加`will-change`, 事件或动画完毕，一定要及时`remove`. 比方说点击某个按钮，其他某个元素进行动画。点击按钮`(click)`，要先按下`(mousedown)`再抬起才出发。因此，可以`mousedown`时候打声招呼, 动画结束自带回调，于是（示意，不要在意细节）
```javascript
dom.onmousedown = function() {
    target.style.willChange = 'transform';
};
dom.onclick = function() {
    // target动画哔哩哔哩...
};
target.onanimationend = function() {
    // 动画结束回调，移除will-change
    this.style.willChange = 'auto';
};
```
