### ISSUE TITLE
通过动画延迟属性来创建弹跳加载中动画

### ISSUE THREAD

**Issue by 13916253446** [13916253446/blog#2]
#### HTML
```html
<div class="bouncing-loader">
  <div></div>
  <div></div>
  <div></div>
</div>
```
#### CSS
```css
@keyframes bouncing-loader {
  from {
    opacity: 1;
    transform: translateY(0);
  }
  to {
    opacity: 0.1;
    transform: translateY(-1rem);
  }
}
.bouncing-loader {
  display: flex;
  justify-content: center;
}
.bouncing-loader > div {
  width: 1rem;
  height: 1rem;
  margin: 3rem 0.2rem;
  background: #8385aa;
  border-radius: 50%;
  animation: bouncing-loader 0.6s infinite alternate;
}
.bouncing-loader > div:nth-child(2) {
  animation-delay: 0.2s;
}
.bouncing-loader > div:nth-child(3) {
  animation-delay: 0.4s;
}
```
![动画](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/Kapture%202018-10-18%20at%2010.48.34.gif?q-sign-algorithm=sha1&q-ak=AKIDjrZeILwyGkOUrB63gl5aecj3YDd3y1Yt&q-sign-time=1539831144;1539832944&q-key-time=1539831144;1539832944&q-header-list=&q-url-param-list=&q-signature=59a6dcae9e1c6d0e15db94eff12fe54e392299e2&x-cos-security-token=6bb1edefc5f749d42056b627e0c67520e4cec5e210001&response-content-disposition=attachment)
