### ISSUE TITLE
项目中的小问题

### ISSUE THREAD

**Issue by 13916253446** [13916253446/blog#21]
### 设置多行文字溢出的时候`-webkit-box-orient`会被移除掉
```css
.ellipsis2 {
    display: -webkit-box;
    text-overflow: ellipsis;
    overflow : hidden;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical
}
```
#### 解决方法：
```css
// 关闭autofixer
.ellipsis2 {
    display: -webkit-box;
    text-overflow: ellipsis;
    overflow : hidden;
    -webkit-line-clamp: 2;
    /* autoprefixer: off */
    -webkit-box-orient: vertical
    /* autoprefixer: on */
}
```
