### ISSUE TITLE
css实用技巧

### ISSUE THREAD

**Issue by hfc-advance** [13916253446/blog#3]
## 1. 设置选中文本的样式
```css
::selection {
  background: aquamarine;
  color: black;
}
.custom-text-selection::selection {
  background: deeppink;
  color: white;
}
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/Kapture%202018-10-18%20at%2011.18.14.gif?q-sign-algorithm=sha1&q-ak=AKIDeT2IzIr2bveYwwc9G9OxANDOuwggXmj6&q-sign-time=1539832771;1539834571&q-key-time=1539832771;1539834571&q-header-list=&q-url-param-list=&q-signature=e260d3d6dd14477b0f54a25df679ec08ca10683b&x-cos-security-token=4b0fab7de5d092290b30186f4fc6e53a7bdb6ec510001&response-content-disposition=attachment)

## 2. 创建动态阴影（根据元素的背景色来创建）
```html
<div class="dynamic-shadow-parent">
  <div class="dynamic-shadow"></div>
</div>
```
```css
.dynamic-shadow-parent {
  position: relative;
  z-index: 1;
}
.dynamic-shadow {
  position: relative;
  width: 10rem;
  height: 10rem;
  background: linear-gradient(75deg, #6d78ff, #00ffb8);
}
.dynamic-shadow::after {
  content: '';
  width: 100%;
  height: 100%;
  position: absolute;
  background: inherit;
  top: 0.5rem;
  filter: blur(0.4rem);
  opacity: 0.7;
  z-index: -1;
}
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/WX20181018-133155.png?q-sign-algorithm=sha1&q-ak=AKIDyrMJ5JAfwrJuYNTVXDUPCoRgisVD0JuU&q-sign-time=1539840748;1539842548&q-key-time=1539840748;1539842548&q-header-list=&q-url-param-list=&q-signature=66c5fba1da0d03e6bf3e47ce848fbdf430be2f19&x-cos-security-token=8575a52f0b281cb61a1691d3a565a6e5a2ac08fd10001&response-content-disposition=attachment)

## 3. 创建渐变文字
```html
<p class="gradient-text">崔海峰</p>
```
```css
.gradient-text {
  background: -webkit-linear-gradient(blue, red);
  -webkit-text-fill-color: transparent;
  -webkit-background-clip: text;
}
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/WX20181018-134004.png?q-sign-algorithm=sha1&q-ak=AKID1Fn7V6QG2MVTLprVpIwwBR6zyWsN7MpH&q-sign-time=1539841343;1539843143&q-key-time=1539841343;1539843143&q-header-list=&q-url-param-list=&q-signature=b42194dd66a94ad0a8bac1dbe908e8131721382e&x-cos-security-token=24c2f295cf40e844b81f107db6d13c9876ab9db610001&response-content-disposition=attachment)
`background: -webkit-linear-gradient(...)` 为文本元素提供渐变背景。
`webkit-text-fill-color: transparent` 使用透明颜色填充文本。
`webkit-background-clip: text` 用文本剪辑背景，用渐变背景作为颜色填充文本。

## 4. 创建鼠标渐变跟踪
```html
<button class="mouse-cursor-gradient-tracking">
  <span>Hover me</span>
</button>
```
```css
.mouse-cursor-gradient-tracking {
  position: relative;
  background: #7983ff;
  padding: 0.5rem 1rem;
  font-size: 1.2rem;
  border: none;
  color: white;
  cursor: pointer;
  outline: none;
  overflow: hidden;
}
.mouse-cursor-gradient-tracking span {
  position: relative;
}
.mouse-cursor-gradient-tracking::before {
  --size: 0;
  content: '';
  position: absolute;
  left: var(--x);
  top: var(--y);
  width: var(--size);
  height: var(--size);
  background: radial-gradient(circle closest-side, pink, transparent);
  transform: translate(-50%, -50%);
  transition: width 0.2s ease, height 0.2s ease;
}
.mouse-cursor-gradient-tracking:hover::before {
  --size: 200px;
}
```
```javascript
var btn = document.querySelector('.mouse-cursor-gradient-tracking')
btn.onmousemove = function(e) {
  var x = e.pageX - btn.offsetLeft
  var y = e.pageY - btn.offsetTop
  btn.style.setProperty('--x', x + 'px')
  btn.style.setProperty('--y', y + 'px')
}
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/Kapture%202018-10-18%20at%2013.50.01.gif?q-sign-algorithm=sha1&q-ak=AKIDR3vywZcIOyomPpC0CloHnK02ityUKjm8&q-sign-time=1539841832;1539843632&q-key-time=1539841832;1539843632&q-header-list=&q-url-param-list=&q-signature=6a728c469ead3c01c34b11070333182918c18e68&x-cos-security-token=4d1cd86c05569e5342349fae2217712602adfd9b10001&response-content-disposition=attachment)
#### 注意！
如果元素的父级具有定位上下文(position: relative )，您还需要减去它的偏移量。

`var x = e.pageX - btn.offsetLeft - btn.offsetParent.offsetLeft`
`var y = e.pageY - btn.offsetTop - btn.offsetParent.offsetTop`

## 5. 向溢出元素添加渐变以更好地指示有更多内容需要滚动
```html
<div class="overflow-scroll-gradient">
  <div class="overflow-scroll-gradient__scroller">
    Content to be scrolled
  </div>
</div>
```
```css
.overflow-scroll-gradient {
  position: relative;
}
.overflow-scroll-gradient::after {
  content: '';
  position: absolute;
  bottom: 0;
  width: 240px;
  height: 25px;
  background: linear-gradient(
    rgba(255, 255, 255, 0.001),
    white
  ); /* transparent keyword is broken in Safari */
  pointer-events: none;
}
.overflow-scroll-gradient__scroller {
  overflow-y: scroll;
  background: white;
  width: 240px;
  height: 200px;
  padding: 15px 0;
  line-height: 1.2;
  text-align: center;
}
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/Kapture%202018-10-18%20at%2014.00.21.gif?q-sign-algorithm=sha1&q-ak=AKIDCQpnnjWhLr1tMXvZbqdY0DWcXX0A54hK&q-sign-time=1539842455;1539844255&q-key-time=1539842455;1539844255&q-header-list=&q-url-param-list=&q-signature=7ab1573896f142a29af453d04d0f9e25f41190e9&x-cos-security-token=7c74975474b28ff11a054108288c2cbdad6d365710001&response-content-disposition=attachment)

## 6. css实现文字两端对齐
> 红框所在的文字有四个字的、三个字的、两个字的，如果不两端对齐可以选择居中对齐，或者右对齐。但是如果要想文字两端对齐呢？
```html
<div>姓名</div>
<div>手机号码</div>
<div>验证码</div>
<div>账号</div>
<div>密码</div>

div{
    margin:10px 0; 
    width:100px;
    border:1px solid red;
    text-align-last: justify;
}
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/68747470733a2f2f7773322e73696e61696d672e636e2f6c617267652f303036744e633739677931666a76767931636732326a33306b733066743075772e6a7067.jpeg?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDIPGsHRg5ZpqgIgwkQt76pIWUDgtrsT7Y%26q-sign-time%3D1541401732%3B1541402632%26q-key-time%3D1541401732%3B1541402632%26q-header-list%3D%26q-url-param-list%3D%26q-signature%3D32e105fa91b610b2e5545cd2784401aa862dbbd7)
**text-align-last最后一行被调整为两端对齐。**
