### ISSUE TITLE
环形旋转器

### ISSUE THREAD

**Issue by 13916253446** [13916253446/blog#4]
#### HTML
```html
<div class="donut"></div>
```

#### CSS
```css
@keyframes donut-spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
.donut {
  display: inline-block;
  border: 4px solid rgba(0, 0, 0, 0.1);
  border-left-color: #7983ff;
  border-radius: 50%;
  width: 30px;
  height: 30px;
  animation: donut-spin 1.2s linear infinite;
}
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/Kapture%202018-10-18%20at%2011.32.03.gif?q-sign-algorithm=sha1&q-ak=AKIDWePTxytFZ7D2NdYeRnR4PcN9XeWBSlMk&q-sign-time=1539833560;1539835360&q-key-time=1539833560;1539835360&q-header-list=&q-url-param-list=&q-signature=90af809278b7651d5da97b9f17940b4813909f27&x-cos-security-token=e5c51fbcccbeb4e95aed9421df0af69e042ba47b10001&response-content-disposition=attachment)
