### ISSUE TITLE
css干货

### ISSUE THREAD

**Issue by 13916253446** [13916253446/blog#44]
## 设置文字居中，一行文字居中，多行文字的时候左对齐
```html
<div class='container'>
    <p class='child'></p>
</div>
```
```css
.container {
    text-align: center;
}
.child {
    display: inline-block;
    text-align: left;
}
```
父元素设置居中对齐，内部元素设置左对齐，并且设置成行内块状元素，设置成行内元素不行，因为行内元素不能设置宽和高以及对齐方式，所以没用
