### ISSUE TITLE
创建半透明边框

### ISSUE THREAD

**Issue by 13916253446** [13916253446/blog#6]
默认情况下，背景的颜色会延伸至边框下层，这意味着我们设置的透明边框效果会被覆盖掉，在css3中，我们可以通过设置`background-clip:padding-box`来改变背景的默认行为，达到我们想要的效果。
```css
  main{
    width: 100%;
    padding: 60px 80px 80px;
    background: #b4a078;
  }
  div{
    padding: 12px;
    margin: 20px auto;
    background: white;
    border: 10px solid hsla(0, 0%, 100%, .5);
   background-clip: padding-box;
  }
  label{
    color: #f4f0ea;
  }
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/jldjlsd.png?q-sign-algorithm=sha1&q-ak=AKIDSDjTvCQWjGHpmwiyfwpVj22UXX1MERw9&q-sign-time=1539851886;1539853686&q-key-time=1539851886;1539853686&q-header-list=&q-url-param-list=&q-signature=353bd605b68d3e9ee47121d0f1d872d8d9541b74&x-cos-security-token=f4b0ad22faaf396b7f8ed9bd9dadd1fbfdd1a8fe10001&response-content-disposition=attachment)
