### ISSUE TITLE
创建边框内圆角

### ISSUE THREAD

**Issue by hfc-advance** [13916253446/blog#7]
我们知道`box-shadow`是会紧贴`border-radius`圆角边的，但是，描边`outline`并不会与圆角边`border-radius`贴合，我们可以将两者组合，通过`box-shadow`去填补描边`outline`所产生的间隙来达到我们想要的效果。

> 关于扩张半径的取值？假设圆角border-radius的半径为r,根据勾股定理，扩张半径的最小值应等于(√2−1)r ~= 3.314，最大值不能超过描边宽度，即6px。
```html
 <input id="ck" type="checkbox" checked/>
    <label for="ck">box-shadow</label>
    <div>A paragraph of filler text. La la la de dah de dah de dah de la.</div>
```
```css
main{
    width: 100%;
    padding: 60px 80px 80px;
  }
  div{
    width: 209px;
    margin: 29px auto;
    padding: 8px 16px;
    border-radius: 8px;
    background: #f4f0ea;
    outline: 6px solid #b4a078;
  }
  input{
    margin-left: calc(50% - 45px);
  }
  input:checked ~ div{
    box-shadow: 0 0 0 5px #b4a078;
  }
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/djlfdl.png?q-sign-algorithm=sha1&q-ak=AKIDobEoGQQYn4uBskvdOVaNfZM5kW0jpaqy&q-sign-time=1539854765;1539856565&q-key-time=1539854765;1539856565&q-header-list=&q-url-param-list=&q-signature=f800c5df92345ea7dcc490d55b02c700576af747&x-cos-security-token=1660f56c9f57e4efa5f3fc603ffcc3dd278a381a10001&response-content-disposition=attachment)
