### ISSUE TITLE
你不知道的border-radius

### ISSUE THREAD

**Issue by 13916253446** [13916253446/blog#8]
#### `border-radius`单值
我们将`border-radius: 300px`还原成其整容前的模样，结果是：
```css
border-radius: 300px 300px 300px 300px/300px 300px 300px 300px;
```
虽然看上去都是300px, 长得好像一样，实际上，表示的含义各不相同，翻译成普通话就是：
```css
border-radius: 左上角水平圆角半径大小 右上角水平圆角半径大小 右下角水平圆角半径大小 左下角水平圆角半径大小/左上角垂直圆角半径大小 右上角垂直圆角半径大小 右下角垂直圆角半径大小 左下角垂直圆角半径大小;
```

> 也就是斜杠前的是水平方向，斜杠后面的是垂直方向。

对于正圆，我们基本上很少提“水平半径”和“垂直半径”，因为，半径都是一样长。但是，对于标准椭圆，那就不一样了，因为存在最长半径和最小半径。在web中，圆角的水平半径指的就是椭圆的水平半径，垂直半径就是椭圆下图所示的垂直半径：
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/2015-11-01_191017.png?q-sign-algorithm=sha1&q-ak=AKIDXNPyzk5wT2VntJP9sYyIZaVjGykH19H9&q-sign-time=1539861968;1539863768&q-key-time=1539861968;1539863768&q-header-list=&q-url-param-list=&q-signature=361061998db60f35d22581f46d280ab8b022e646&x-cos-security-token=0dcda17684d65d5faa7da125cccac6f4ba1c000110001&response-content-disposition=attachment)

一个水平半径和一个垂直半径所夹起的那1/4段圆弧就是我们平时看的的圆角呈现，如下变色显示：
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/2015-11-01_191017-highlight.png?q-sign-algorithm=sha1&q-ak=AKIDezszXrYRQ8cpPV86CzOAgXSthkRhmNAL&q-sign-time=1539862035;1539863835&q-key-time=1539862035;1539863835&q-header-list=&q-url-param-list=&q-signature=63d063c8e0bb4f211a55dc759dfbf50e79d56e03&x-cos-security-token=4a49413a58d4c7d43522455274d8c67e9c789d0110001&response-content-disposition=attachment)
### border-radius 创建圆和椭圆
```html
<main>
    <div class="ellipse"></div>
    <div class="ellipse"></div>
    <div class="ellipse"></div>
    <div class="ellipse"></div>
    <div class="ellipse"></div>
    <div class="ellipse"></div>
</main>
```
```css
main{
    width: 100%;
    padding: 60px 0;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
  }
  div{
    width: 200px; height: 150px;
    background: #b4a078;
    margin-bottom: 30px;
  }
  .ellipse:nth-of-type(1){
    width: 300px; height: 150px; 
    border-radius: 50% / 100% 100% 0 0;
  }
  .ellipse:nth-of-type(2){
    width: 150px; height: 150px;
    border-radius: 100% 0 0 0;
  }
  .ellipse:nth-of-type(3){
    border-radius: 50% / 100% 100% 0 0;
  }
  .ellipse:nth-of-type(4){
    width: 100px;
    border-radius: 100% 0 0 0;
  }
  .ellipse:nth-of-type(5){
    width: 300px;
    border-radius: 50% / 0 100%;
  }
  .ellipse:nth-of-type(6){
    width: 300px;
    border-radius: 50% / 100% 0;
  }
```
![result](https://mp1-1252842252.cos.ap-shanghai.myqcloud.com/djlfkdlnfkl.png?q-sign-algorithm=sha1&q-ak=AKIDMBxVhiMtrZ57fGeT0R3pZcucnjtdnkbK&q-sign-time=1539862476;1539864276&q-key-time=1539862476;1539864276&q-header-list=&q-url-param-list=&q-signature=54fa40265fe8dfa5c01c8c4ca4efaaee7a0e3a14&x-cos-security-token=05dab2464c1117832be9d13c84c242631aabd48e10001&response-content-disposition=attachment)

#### 最后带上张大神的实时[demo](https://www.zhangxinxu.com/study/201511/demo-border-radius.html)
