### ISSUE TITLE
实用选择器

### ISSUE THREAD

**Issue by 13916253446** [13916253446/blog#9]
### 兄弟选择器`+`
紧跟前面的元素的选择器
```css
* + * {    
    margin-top: 1.5rem;  
}
```
